#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
import setuptools

with open('README.txt') as readme:
	long_description = readme.read()
with open('CHANGES.txt') as changes:
	long_description += '\n\n' + changes.read()

setup_params = dict(
	name='backports.functools_lru_cache',
	use_hg_version=True,
	author="Raymond Hettinger",
	author_email="raymond.hettinger@gmail.com",
	maintainer="Jason R. Coombs",
	maintainer_email="jaraco@jaraco.com",
	description="backports.functools_lru_cache",
	long_description=long_description,
	url="https://bitbucket.org/jaraco/backports.functools_lru_cache",
	packages=setuptools.find_packages(),
	namespace_packages=['backports'],
	setup_requires=[
		'hgtools',
	],
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"Intended Audience :: Developers",
		"Programming Language :: Python :: 2.6",
		"Programming Language :: Python :: 2.7",
		"Programming Language :: Python :: 3",
	],
)
if __name__ == '__main__':
	setuptools.setup(**setup_params)
